name: Build and deploy package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test


      - name: Create the Package
        run: dotnet pack --configuration Release 
        

      - name: Publish
        run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -K ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json

    